mikhael28/paretOS

src/profile/Login.js

refactored Login from a class to a hook

---

src/profile/ResetPassword.js

refactor: ResetPassword to functional component

---

src/profile/Signup.js

Pls test and see what you think

Refactor signup with hooks #7

---

src/context/ContextBuilder.js

- Refactor Class component to function component
- Use React.Children so indices are not used as keys for map method
closes #42

feat: ContextBuilder - Implement hooks

---

src/index.css
src/learn/ExperienceSummary.js

changed the active component background color. changed the background color, and color when component is hovered.

ui suggestion for ExperienceSummary.js

---

src/arena/ArenaDashboard.js

feat: ArenaDashboard - Implement hooks

---

src/context/SuggestionModal.js

♻️ refactor(SuggestionModal): convert class based component to hooks

---

src/components/LeftNav.js
src/libs/strings.js
src/profile/EditProfile.js

Hope you enjoy it! Any considerations, let me know please.

[FEATURE] adding pt-br localization to the project

---

CONTRIBUTING.MD

adding initial code of conduct, per OSS best standards (thanks Atom!)

adding initial code of conduct

---

src/components/LeftNav.js
src/libs/strings.js
src/profile/EditProfile.js

- Added hindi language.
- From line 1355 to 1532.
- #112

Improve feature

---

src/Routes.js
src/profile/EditProfile.js
src/profile/Languages.js

@mikhael28 I believe I finally resolved my issues. I did console everything to make sure all the data was correct. 
- Changed language component into a functional while adding spinner while loading button
- #104  or whichever ticket number the pr is addressing
- @person2
- ...
...

resolved language component and added isloading spinner at fetch api

---

package.json
src/components/Board.spec.tsx
src/components/Board.tsx

I'm coming back around to the requests to migrate to TypeScript and add Enzyme shallow render tests. Opening as a draft for now so you can review the TypeScript migration, but I'll add some tests soon as well in an additional commit.
- Initial refactor of leaderboard component to typescript
Fixes #75 
See also #129 for prior discussion!

Initial refactor to TypeScript

---

package.json
src/Routes.js
src/components/Spinner.js
src/index.js

- Updated Routes.js to include lazy loading of route components. which reduces the bundle size.
- [#18](https://github.com/mikhael28/paretOS/issues/18)
- @mikhael28

:racehorse: add lazy loading routes

---

package.json
src/Routes.js
src/profile/Login.js
yarn.lock

- Added login form validation using ```react-hook-form```.
- Form validation includes invalid emails and passwords, as well as requiring the fields.
- I also updated Routes.js and modified how the 3 Route components were imported because they should not use lazy loading.
- #8 
- @mikhael28

Add login form validation

---

public/index.html
src/arena/SprintCreation.js
src/containers/HooksSandbox.js
src/libs/pwa.js

I've gone ahead and added a Hooks Sandbox component out of some notes from some articles/YouTube videos I have on good code that can be added into the project at some point, specifically the `array` hook which creates some new prototypical methods for the arrays used as helper functions.

Added a Hooks sandbox for future implementation of functionality

---

src/components/Board.spec.tsx
src/tests/Board.spec.tsx

Hi @jayeclark, I was wondering if these tests are similar to what you're looking for.
I must mention that there is an issue with one of the tests so far. The input for filtering the leaderboard doesn't seem to accept values. I tried using fireEvent.change to add a value to the input. (You can see how I wrote the test.) In theory, it should work. I'll try to debug it
- Added some tests for the table in the Leaderboard component
- #150

Add more tests to leaderboard component

---

src/profile/CreateUser.js
src/profile/EditProfile.js

- Refactored CreateUser and EditProfile class components to functional components
- Fixed errors that arose
- #189
- @jayeclark

Refactor: CreateUser and EditProfile from a class to a function component

---

src/App.js

Fixes state bugs introduced by recent App.js refactoring.
- Reverts setting user/language to its own state update
- connectSocketToSprint is now dependent on user state again
- #203 
- @mikhael28

Fix state bugs

---

src/profile/ResetPassword.js

- Removed Glyphicon check mark
- Added reaction-icons check mark
- #179 or whichever ticket number the pr is addressing
- @person2
- ...
...

change: removed Glyphicon check added react-icon

---

PULL_REQUEST_TEMPLATE.md

Change last level 3 heading to match the other level 2 headings.
- @mikhael28

chore: update PULL_REQUEST_TEMPLATE.md heading

---

public/index.html
src/App.js
src/arena/CreateSprintTemplate.js
src/index.css

Remove all unnecessary over-scroll.
- #170 
- @mikhael28 
- @jayeclark 
Example of one of the affected pages
**Before**
**After**

fix: remove all unnecessary scrolls

---

package.json
src/arena/Missions/Index.tsx
src/containers/Home.tsx
src/containers/Palette.tsx
src/containers/Sandbox.tsx
src/context/ContextBuilder.js
src/context/ContextObject.tsx
src/context/ContextPage.js
src/context/ContextTypes.ts
src/libs/initialFetch.ts
src/libs/websocket.ts
src/utils/getFormattedDay.ts
tsconfig.json
yarn.lock

Just did some quick TypeScript typing, getting ready for work on the library of context - and while I was at it, made the no-implicit-any typescript rule mandatory. @jayeclark would you please pull these changes into your PR for refactoring App.js into TypeScript, and address any potential no implicit any's that have been overlooked? I'm about to head out to the conference, and will take a look at your PR tonight when I get back.

changed no implicit any to true, started typing library of context stuff

---

package.json
pnpm-lock.yaml
src/arena/CreateSprintTemplate.tsx

Pulled PR into its own branch to fix merge conflicts & re-run CI

Convert create sprint template issue#246

---

package.json
pnpm-lock.yaml
src/arena/CreateSprintTemplate.tsx

converted CreateSprintTemplate.js to CreateSprintTemplate.tsx
- #246 
- @person2

converted JS file to typescript

---

src/learn/ApproveExperienceModal.jsx

Resolves merge conflicts for PR #229

Resolve merge conflicts from AleksandrKurilov PR

---

src/learn/ApproveExperienceModal.jsx

Reverts mikhael28/paretOS#252
(In the process of fixing the merge conflict the commit history got messed up ... reverting & trying via another route so the original author retains credit for the commit/PR)

Revert "Resolve merge conflicts from AleksandrKurilov PR"

---

package.json
pnpm-lock.yaml

Trying this quick fix as a first step to fix the broken AWS CI.  If it doesn't work, I've got a few other tricks to try.

Try tweaking dependencies to fix build

---

vite.config.js

Testing potential fix for deployment via configuration. I'm still not able to reproduce in my local environment or on Docker, no matter which version of Node I use.

Testing config fix

---

src/profile/Signup.tsx

- Updated Signup.jsx file to change rendering logic
- #279
- @mikhael28  (merge duty)
- @jayeclark
1. Go to the [ParetOS](https://www.paret0.com/) website
2. Choose the signup option
3. Redirects to code confirmation page before actual sign up

:bug: fix sign up issue

---

.git.code-workspace
package.json
pnpm-lock.yaml
src/profile/Signup.tsx

Description
- Refactored Signup.tsx forms react-bootstrap -> react-hook-form migration
- Added "yup" dependency to ease form validation
Relates to
- #298

Refactored Signup forms: react-bootstrap -> react-hook-form migration

---

src/profile/LanguageSelector.tsx

Updated to MUI select form and react hook form
- #297 
- @person2
jayeclark or mikhael28, not me!

Languageselector migration#297

---

src/containers/Palette.tsx

- Fix page navigation
- remove name duplicate
- #260 
...

Command pallete polish

---

src/App.tsx
src/Routes.tsx
src/arena/CreateSprintTemplate.tsx
src/arena/Sprint.tsx
src/arena/SprintCreation.tsx
src/components/Board.tsx
src/learn/ExperienceModule.tsx
src/learn/Order.tsx
src/profile/Login.tsx
src/profile/Signup.tsx

- Updated some file to change some logic
- Added tests
- Updated docker-compose.yml to include new ENV
- #34 or whichever ticket number the pr is addressing
- @person2
- ...
...

fix: fixed issues talked about

---

src/profile/Login.tsx
src/profile/Signup.tsx

- Updated Login component to have Link for redirection to home page from Pareto logo
- #305 
- @jeremydthomas 
- @mikhael28 
- Open the application in a browser and go to login page
- Click the Pareto logo
- Expect redirection to Home page

#305 link to home from login page

---

package.json
tests/integration/login.test.ts
tests/integration/vite.config.js

See [this action workflow](https://github.com/jayeclark/_paretOS/actions/runs/3963289576) for proof of concept.
- Fixes CI issues by removing preview server & a few other tweaks
- Adds separate configs for unit & integration tests (these could be combined but I think it makes it easier to pinpoint where failures are happening.)
- Will need to do some additional upgrades (some of the setup is running on a deprecated version of Node) but this should get the CI functioning at a base level again.
- Also some eslint fixes to vite config file
N/A
- @mikhael28
- @jeremydthomas

Fix test configuration

---

package.json
pnpm-lock.yaml
src/index.jsx

- Upgrades aws-amplify auth dependency
- Corrects the issue causing the error that is breaking CI for the dependabot request.
- #424

Upgrade amplify auth and add configuration

---

src/profile/LanguageSelector.tsx
src/profile/Login.tsx
src/profile/ResetPassword.tsx
src/profile/Signup.tsx

- Added homepage link to logo in user creation related forms
- Fixed some typescript errors
- #306 
- @person2
- ...
...

Logo in form pages navigates to homepage

---

src/profile/EditProfile.tsx

- Replace react bootstrap with material ui
- #296 EditProfile.tsx react-bootstrap -> react-hook-form migration
- 
- @person2
- ...

Migrate from react-bootstrap to material

---

package.json
src/App.tsx

Upgrading dependabot recommendations manually since something seems to be broken with the Vercel builds initiated by those pull requests, and I don't have access to the Vercel account to troubleshoot.
#439, #438, #436, #432, #429

Bump dependency versions recommended by dependabot

---

src/arena/CreateSprintTemplate.tsx
src/components/LeftNav.tsx
tests/integration/CreateSprintTemplate.test.ts
tests/integration/install-mouse-helper.js

added e2e test with puppeteer, from login to logout
- #452  
- @person2

447 create sprint template test

---

src/profile/EditProfile.tsx

Quick bug fix PR - adds a few minor updates to EditProfile state so that profile photo will update when the user saves a new image. Hopefully the final stage in fixing this page now that the backend API has been debugged.

Fix: edit profile state
