mikhael28/paretOS

- src/context/ContextBuilder.js
- src/index.css
Context: The nav bar would break around 600px width and on really small viewports. This was due to a css rule from material ui creating a min-width on the buttons in the nav. I gave the navbar buttons all a rule overruling the MUI rule and this fixed the issue. 
Before:
After:
Context: On mobile/tablets going to the bottom of the screen, the navbar would overlap content. I was able to fix this issue on the library of context, I just added a class to the tab container which holds all the media cards. I then added a margin-bottom rule to this class and made it responsive by using vh units thus there's no obscenely large gap on any viewports. I made a similar fix with the mentorship page, the container already had a class defined however so it was just adding a margin-bottom rule to it. …
> #11 bug fix : gap between content and nav / fixing navbar/logout on mobile.

- src/components/ArenaProofModal.js
- src/learn/NewSubmitProofModal.js
- src/libs/s3.js
Converted class components to hooks based on issue #52. I can't really test this component in the browser because I think you need to pay to get access to this page, so I'd be grateful if you could check it out with a paid account(or give me the credentials to that accounts, for testing). Currently, I've checked through the code and there are no errors with SonarLint(IDE plugin) and CRA(create-react-app). 
Also, I'd like to address this todo on line 33:
```javascript
// @TODO: Is this function repetitive? With Arena proof modal?
```
I think it is repetitive and maybe we refactor the following logic into a utility function/service:
```javascript
let pictureKey = await Storage.put(
`${this.props.sprint.id}_0_${this.props.day}_${this.props.activeIndex}.${fileType[1]}`,
file,
{
bucket: …
```
> ♻️  refactor(NewSubmitProofModal): converted class component to hooks

- src/arena/Sprint.js
- src/components/Board.js
- src/components/PageNavigation.js
- src/components/ProfileImg.js
- src/index.css
Enhances Leaderboard appearance (leaderboard logic/ranking/score attribution will be addressed in a separate PR.)
Additional improvements:
Partially addresses #75
> Refactor Leaderboard to use hooks

- src/components/Board.spec.tsx
- src/components/Board.tsx
- Fixes error in Leaderboard typing (my last PR accidentally defined planning to be a string, when it should be an array)
- #131 
- @mikhael28  (merge duty)
> Fix board type issue

- src/arena/SprintCreation.js
Temporarily fixes #147 by adding a div wrapper around the LoaderButton component.
#147 , #141 
- @mikhael28  (merge duty)
- @vmcodes (for visibility since IIRC you're working on forms) 
See bug report.
> Temporary fix for loader button

- src/components/LeftNav.js
I just fired up the merged changes on main to take new photos for the Readme, and noticed that I had accidentally changed Library of Context to be styled as a sub-header. (It was a copy-paste error when I updated the style variable names.) 🤦  
- #153
> Fix left nav style bug

- src/index.css
- src/profile/Login.js
- src/profile/Signup.js
- Fixes logo display to be inverted if site is in dark mode
- Adds a temporary inline styling fix for the Material UI input background color/text color mismatch bug 
- Adds a temporary override in index.css for a bootstrap style that conflicts with the MUI button. 
Temporarily fixes #164 with inline styling, but I'll also open a ticket seeking a longer-term solution. (The MUI background/text mismatch is going to be an issue across ALL forms they get converted.)
- @mikhael28  (I'm going to merge immediately so new contributors can actually see the sign in form as they're trying to create their test accounts, but please review!)
> Fix MUI style issues (unreadable form fields, black-on-black text) & logo color

- package.json
- src/App.js
As the description says, removing this package to avoid stupid amounts of connections being added to our Dynamo table.
> Removing reconnecting websocket npm package

- src/components/LoaderButton.tsx
- src/profile/EditProfile.js
Adds optional chaining & a conditional value to LoaderButton to circumvent the errorToast notification not being able to consume the theme. This should be revisited/removed once toast notifications are migrated to a better library - with most other libraries, this would not be an issue. (See #30 )
Fixes #171 
- @mikhael28  (for visibility)
See original bug report
> Fix error toast notifications

- src/arena/Sprint.js
Pull-Request for `paretOs` 
- Updated [Sprint.js](https://github.com/mikhael28/paretOS/blob/main/src/arena/Sprint.js). Have a variable for all missions, finished missions, and daily missions to avoid repeating code when checking if there are completed or daily missions .
- #158
- @jayeclark
- @mikhael28 
- Make request or go to `/arena/sprints/:id` 
- Expect some response(all missions in particular).
I changed some div to section, ul and li tags just to use the appropriate semantic elements.
> fix: daily/finished acheivements messages when empty

- src/arena/SprintCreation.js
- src/components/LoaderButton.tsx
- src/index.css
- src/learn/ExperienceModule.js
Replaces the `react-bootstrap` Glyphicon components in three files with icons from `react-icons` that have a very similar appearance. (Small bit of UI cleanup as well.)
Partially addresses #179 
- @mikhael28
> Bootstrap migration: remove glyphicons in SprintCreation, LoaderButton, ExperienceModule

- src/profile/Login.js
- Updated Login.js file to changes the input text color and the label color
- removing the inline styles
- #166  or whichever ticket number the pr is addressing
- @jayeclark 
- ...
> Login page backgroud and input text color changed as primary color

- src/arena/CreateSprintTemplate.js
- src/arena/Sprint.js
- src/arena/SprintCreation.js
- src/libs/theme.js
- Changed Button to material UI component in CreateSprintTemplate 
- Changed Button to IconButton in SprintCreation
- Changed Button to material UI Button and Chip in Sprint
- Added Button gradient variant and Chip variant to `libs/theme`
- [Refactor:  Migrate react-bootstrap Button component to MaterialUI](https://github.com/mikhael28/paretOS/issues/177)
- @jayeclark 
- @mikhael28
> Migrate react-bootstrap Button component in arena to MaterialUI Issue #177

- src/profile/EditProfile.js
Updated EditProfile.js by removing import Glyphicon from "react-bootstrap/lib/Glyphicon"
Added import { BsPencil, BsPlusLg } from "react-icons/bs";
Removed the Glyphicon Pencil mentions and added BsPencil, while trying to make it look better.
Removed the Glyphicon Plus mentions and added BsPlusLg, while lining it up to BsPencil and tried to make it eye pleasing.
- #179 
- @person2
- ...
...
some other info, while making my changes, I noticed that clicking on the projects plus sign i get this error.
so, I discarded my changes thinking it was me who did it. However, the error is still there.
> 'Removed Glyphicon and added react-icons to EditProfile'

- src/index.js
- src/libs/s3.js
Updates AWSAmplify configuration to fix bucket name and add region, fixes deprecated imports & syntax. (I also fixed the bucket policy on the back end which was the majority of the work here.) 
Proof of daily achievements now uploads to S3 as intended and is available for users to download! Currently it just downloads rather than being displayed, so, I may open a ticket for that refinement. 
- Fixes #140 
- @mikhael28 
Screenshot showing proof link and downloaded proof.
> Fix S3 proof uploading failure

- package.json
- src/App.js
- src/arena/CreateSprintTemplate.js
- src/arena/SprintCreation.js
- src/arena/Sprints.js
- src/context/SuggestionModal.js
- src/index.js
- src/learn/ExperienceModule.js
- src/learn/LearnDashboard.js
- src/learn/Order.js
- src/libs/createExperience.js
- src/libs/errorEmail.js
- src/libs/initialFetch.ts
- src/libs/languages.js
- src/mentorship/MenteeProfile.js
- src/profile/ChangePassword.js
- src/profile/CreateUser.js
- src/profile/EditProfile.js
- src/profile/Login.js
- src/profile/ResetPassword.js
- src/profile/Signup.js
- yarn.lock
- Uses @aws-amplify/api-rest instead of @aws-amplify/api
- Eliminates need for GraphQL dependency bundle
- Reduces bundle size by ~100kb
- Fixes deprecated default imports for Amplify API, Storage, and Auth
I'm still experimenting, but I believe we'll initially want to just replace the Amplify API with fetch (unless you decide we're concerned about supporting IE and Opera Mini). So far it doesn't look like there's anything we need the API module to do at present (even sending auth headers) that can't be done in ~50 lines of code with a custom RestAPI class based around fetch.  
React-Query has some great features, but I'm not sure most of the bells & whistles currently apply to the needs of the project (even the data …
> Convert to RestAPI and fix default imports

- src/arena/Sprint.js
- src/context/ContextObject.tsx
- src/learn/ExperienceModule.js
- src/learn/ExperienceSummary.js
- src/libs/strings.ts
- src/libs/toasts.js
- src/profile/CreateUser.js
- src/profile/EditProfile.js
Code cleanup, removing TODO items that have been addressed in recent PRs.
@mikhael28 How would you feel about removing TODO's that point to GitHub issues and gradually converting relevant remaining TODO's into issues? Right now there are three types of TODO's:
1. **Items pointing to a specific issue on GitHub.** These have no description other than the issue number. I think they were intended to alert contributors that there are additional items they can address when working on a particular file, but, they are difficult to keep up to date, and there are many issues that apply throughout the codebase (tests, migrate to Typescript, migrate to Bootstrap). It feels like expanding the label system might be a less …
> Chore: Remove TODO items that have been addressed

- src/App.js
Fixes initial sprint fetching bug. I think I must have written over my own commit at some point - when connectSocketToSprint is called in the sprint creation process, it runs off of the user id stored in state. However it also needs to be able to accept a direct userID argument because when it is initially called in the site loading process, user state has usually not yet updated (so there is no userID stored in state for the method to draw from.)
Fixes #225 
- @mikhael28
> Fix sprint initial fetch bug

- src/arena/Sprint.js
- src/utils/getDateRange.ts
- src/utils/getFormattedDay.ts
removed the +1 in getDateRange and getFormattedDay that was causing the days to be one day ahead
in getFor4mattedDay added displayDay param and had it add displayDay. displayDay starts at 0 and goes to 5 when clicking on the days in time travel, which causes the days to move ahead depending on day clicked.  added displayDay to the params in Sprint.js in line 239 ```{getFormattedDay(startDate, displayDay)}```
- #3210
- @person2
- ...
...
the above has day 2 clicked and its showing the 9th
> ArenaDateHeader and <section> in TabPanel

- src/App.tsx
- src/context/ContextBuilder.js
- src/libs/initialFetch.ts
- src/profile/CreateUser.js
- src/profile/EditProfile.js
- src/profile/LanguageSelector.js
- src/profile/Login.js
- src/profile/ResetPassword.js
- src/types/index.ts
Initial refactor of App.js to use hooks. Major highlights:
- Reduces file length by nearly 200 lines of code (a lot of this has moved to libs, but we should be able to abstract that even further in a future PR.)
- Applies Promise.all to replace chained awaits where appropriate
- Moves several API queries to their own library for code clarity in App.js
- Refactors the queries so they return values instead of updating state (that way only one state update is needed after Promise.all, I was running into issues with some wonky behavior with batched state updates due to it being a functional component.
- Moves websocket to /libs and fixes a bug where disconnects were causing a new instance of websocket to be created and opened each time the socket disconnected …
> Refactor/convert App.js to use hooks

- .stylelintrc.json
- package.json
- src/index.css
- Removed bootstrap overrides that could be found
- Added stylelintrc.json for Stylelint
- Cleaned up index.css by using Sytlelint. Fixing many errors such as duplicated classes and proper ordering of child classes.
- #201
- @jayeclark 
-Used Stylelint guide here: https://stylelint.io/user-guide/get-started
-Ran command: npx stylelint src/index.css --fix
-Still need to: "Classes that are no longer used anywhere in the project should be removed" &  "Style overrides for material-ui components should happen in theme rather than in index.css."
-This was my first open-source contribution on GitHub, so if I missed anything I apologize and let me know! I would also love some ideas on how to help with the remaining tasks for this issue. I would love to keep helping!
> cleaned up index.css

- .github/workflows/ci.yml
- jest.config.js
- jest.setup.js
- package.json
- pnpm-lock.yaml
- src/tests/Board.spec.tsx
- tests/integration/login.test.ts
- tsconfig.json
- vite.config.js
- Updates CI to use pnpm
- Fixes assorted test suite issues
- Resolves some lingering peer dependency complaints
- #248 
- @mikhael28 
See recent GitHub actions results on my personal fork.
> Fix failing CI after the switch to pnpm/vite

- src/css/index.css
- Updated index.css for removing the scrollbar
- #334
- @mikhael28 
- @jeremydthomas 
- Login to the application in a windows machine
- Expect there are no scroll bars
> #334 fix: Remove the scroll borders on Windows

- package.json
- pnpm-lock.yaml
updated nanoid to version 4, no errors except for experience module didnt work, but I seem to remember you saying that you shut it down on purpose as you were reworking it.
- #330 
- @person2
- ...
> update: updated nanoid to v4

- .github/workflows/ci.yml
- package.json
- pnpm-lock.yaml
- Updates recent dependencies flagged by dependabot (except react-bootstrap and @aws-amplify/auth as those are breaking changes)
- #425, #422, #421
> Update deps and fix ci for dependabot

- src/App.tsx
- src/Routes.tsx
- src/arena/CreateSprintTemplate.tsx
- src/components/AuthenticatedLayout.tsx
- src/components/MusicPlayer.tsx
- src/components/UnauthenticatedLayout.tsx
- src/containers/Palette.tsx
- src/tests/CreateSprintTemplate.spec.tsx
- src/tests/testData.ts
- src/utils/queries/createSprintTemplateQueries.ts
- src/utils/queries/initialFetchQueries.ts
Now that we've got the GitHub actions CI/CD is mostly functioning again (seems like there might still be some issues with the vercel deployment), I'd like to do some work to flesh out the unit & integration tests so that they can actually automatically catch breaking changes in the code. Hopefully with a few example PRs, we can also get new contributors participating as well!
This is the first in a series of PRs to flesh out unit tests related to the arena components (see `arena` folder of repository file structure). Going to leave it open for a bit for review/comments but I don't think this should be too controversial, so will probably merge myself in a few days if no feedback.
* Refactors component to enable external dependencies to more easily be mocked
* Adds some very basic unit …
> Refactor CreateSprintTemplate for easier unit testing and add basic tests
